# Generated by Django 3.0.5 on 2020-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eve_name', models.CharField(max_length=30)),
                ('eve_type', models.CharField(max_length=30)),
                ('dept_faculty_name', models.CharField(max_length=30, unique=True)),
                ('vol_head', models.CharField(max_length=30)),
            ],
        ),
    ]
